[default]

    LEVEL_NAME = "DEBUG"

[development]

    [development.logs]
        LEVEL_NAME = "DEBUG"
        FORMAT = '[%(asctime)s] #%(levelname)-8s %(filename)s:%(lineno)d - %(name)s - %(message)s'
    
    [development.i18n]
        default_locale = "ru"
        locales = ["ru", "en"]

    [development.bot]
        PARSE_MODE = 'HTML'

    [development.postgres]
        # База данных для пользователей
        [development.postgres.users]
            NAME = 'cbc_crew_selection_db'
            HOST = '185.58.204.176'
            PORT = 5434
            USER = 'cbc_bot'
            PASSWORD = 'cbc1337'
        
        # База данных для заявок
        [development.postgres.applications]
            NAME = 'cbc_crew_selection_db_applications'
            HOST = '185.58.204.176'
            PORT = 5435
            USER = 'cbc_bot'
            PASSWORD = 'cbc1337'
    
    [development.redis]
        HOST = 'localhost'
        PORT = 6379
        DATABASE = 1

    [development.nats]
        SERVERS = 'nats://localhost:4222'
        DELAYED_CONSUMER_SUBJECT = 'aiogram.delayed.messages'
        DELAYED_CONSUMER_STREAM = 'delayed_messages_aiogram'
        DELAYED_CONSUMER_DURABLE_NAME = 'delayed_messages_consumer'
    
    [development.cache]
        USE_CACHE = false